sudo: enabled
dist: trusty

before_install:
  # Install Dependencies
  - sudo apt-get update -qq
  - sudo apt-get install linux-headers-$(uname -r)
  - sudo apt-get install autoconf
  - sudo apt-get install automake
  - sudo apt-get install libtool
  - sudo apt-get install pkg-config
  - sudo apt-get install git
  - sudo apt-get install g++
  - sudo apt-get install libssl-dev
  - sudo apt-get install protobuf-compiler 
  - sudo apt-get install libprotobuf-dev 
  - sudo apt-get install libnl-genl-3-dev 
  - sudo apt-get install libnl-3-dev 
  - sudo apt-get install hostapd 

before_script:
  # Make a build directory 
  - mkdir build

script:
  # Run the build script
  - ./install-from-scratch build

