sudo: enabled
dist: trusty

before_install:
  # Install Dependencies
  #- sudo apt-get update -qq
  - sudo apt-get install linux-headers-$(uname -r)
  - sudo apt-get install autoconf
  - sudo apt-get install automake
  - sudo apt-get install libtool
  - sudo apt-get install pkg-config
  - sudo apt-get install git
  - sudo apt-get install g++
  - sudo apt-get install libssl-dev
  #- sudo apt-get install protobuf-compiler
  #- sudo apt-get install libprotobuf-dev
  - sudo apt-get install hostapd
  - sudo apt-get install wpasupplicant

before_script:
  # Make a build and install directory
  - mkdir build
  - mkdir install
  # Install version 2.6.1 of Protocol Buffers
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xvzf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1
  - ./configure && make
  - sudo make install
  - cd ..

script:
  # Run the IRATI stack build script
  - export LD_LIBRARY_PATH=~/install/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=~/install/lib/pkgconfig:$PKG_CONFIG_PATH
  - sudo ldconfig
  - sudo ./configure --prefix ~/install
  - sudo make install
